"""Pure domain rules for the blind module: no framework, database or network imports."""

from listenup.modules.blind.domain.gist import MAX_CHARS, MIN_SENTENCES, count_sentences
from listenup.modules.blind.domain.listen import (
    AHEAD_TOLERANCE_MS,
    BUFFERING_BUDGET_MS,
    CLIENT_VOID_REASONS,
    DEVICE_PAUSE_LIMIT_MS,
    HEARTBEAT_INTERVAL_MS,
    MAX_SILENCE_MS,
    RESUME_DELAY_MS,
    RESUME_REWIND_MS,
    Action,
    Beat,
    Interruption,
    Listen,
    PlayerState,
    Verdict,
    VoidReason,
    client_void,
    heard_whole_passage,
    judge,
)

__all__ = [
    "AHEAD_TOLERANCE_MS",
    "BUFFERING_BUDGET_MS",
    "CLIENT_VOID_REASONS",
    "DEVICE_PAUSE_LIMIT_MS",
    "HEARTBEAT_INTERVAL_MS",
    "MAX_CHARS",
    "MAX_SILENCE_MS",
    "MIN_SENTENCES",
    "RESUME_DELAY_MS",
    "RESUME_REWIND_MS",
    "Action",
    "Beat",
    "Interruption",
    "Listen",
    "PlayerState",
    "Verdict",
    "VoidReason",
    "client_void",
    "count_sentences",
    "heard_whole_passage",
    "judge",
]
