/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request Password Reset
     * @description Email a reset link. The answer is the same whether or not the email has an account.
     */
    post: operations['request_password_reset_api_v1_auth_password_reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset Password
     * @description Set a new password with the token from the email; signs the learner out everywhere.
     */
    post: operations['reset_password_api_v1_auth_password_reset_confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/contents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Contents
     * @description The learner's content items, newest first, in keyset pages.
     */
    get: operations['list_contents_api_v1_contents_get'];
    put?: never;
    /**
     * Add Content
     * @description Confirm an upload: the file must be in storage with the declared size.
     *
     *     Creates a pending content item and queues its conversion. Confirming the same
     *     upload again returns the same item with 200; an `Idempotency-Key` replays the
     *     first response exactly.
     */
    post: operations['add_content_api_v1_contents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/contents/{content_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Content
     * @description One of the learner's items: its processing status, or why it failed, and where
     *     to play it once it is playable.
     */
    get: operations['get_content_api_v1_contents__content_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Events
     * @description Stream the learner's live events (System Design 9.1).
     *
     *     Each event carries only its type and the id of the resource to refetch.
     */
    get: operations['events_api_v1_events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/library/contents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Library Contents
     * @description The learner's library, newest first, 20 per page by default (FR-LB-1).
     */
    get: operations['library_contents_api_v1_library_contents_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['me_api_v1_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/media/{media_object_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Play Media
     * @description The playback file. Redirects to a signed storage URL that serves range requests,
     *     so the player starts on the first bytes and seeks without downloading everything.
     */
    get: operations['play_media_api_v1_media__media_object_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/media/{media_object_id}/peaks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Media Peaks
     * @description The waveform peaks: JSON with `per_second` values a second on a 0 to `scale` range.
     */
    get: operations['media_peaks_api_v1_media__media_object_id__peaks_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/uploads': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Upload
     * @description Check the declared file and return a signed URL to PUT it straight to storage.
     *
     *     Refused before any byte is sent: an unsupported type (`unsupported_file_type`), a
     *     file over the size limit (`file_too_large`), or one that would take the account
     *     over its storage cap (`storage_full`). Rate-limited per learner.
     */
    post: operations['start_upload_api_v1_uploads_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/uploads/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Upload Usage
     * @description How much of the per-account upload storage is used, and the per-file limit (D5).
     */
    get: operations['upload_usage_api_v1_uploads_usage_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/uploads/{upload_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Cancel Upload
     * @description Forget an upload that was cancelled before it was added to the library.
     */
    delete: operations['cancel_upload_api_v1_uploads__upload_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ConfirmUpload
     * @description Add an uploaded file to the library. YouTube links (#37) will be another shape.
     */
    ConfirmUpload: {
      /**
       * Keep Video
       * @description Keep the picture of a video (H.264 360p); otherwise only the sound is kept
       * @default false
       */
      keep_video: boolean;
      /**
       * Title
       * @description Defaults to the file name without its extension
       */
      title?: string | null;
      /**
       * Upload Id
       * Format: uuid
       */
      upload_id: string;
    };
    /**
     * ContentDetail
     * @description One item, with what its page needs to show and play it.
     */
    ContentDetail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Duration Ms */
      duration_ms: number | null;
      /**
       * Error Code
       * @description Why processing failed; null unless failed
       */
      error_code: string | null;
      /**
       * Error Detail
       * @description The reason, as the learner reads it
       */
      error_detail: string | null;
      /**
       * Has Video
       * @description The playback file has a picture (only with keep_video)
       */
      has_video: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Keep Video */
      keep_video: boolean;
      /**
       * Media Object Id
       * Format: uuid
       */
      media_object_id: string;
      /**
       * Media Url
       * @description Play from here (redirects to a signed URL); null until playable
       */
      media_url: string | null;
      /**
       * Peaks Url
       * @description Waveform peaks JSON (redirects to a signed URL); null until playable
       */
      peaks_url: string | null;
      /**
       * Source
       * @enum {string}
       */
      source: 'upload' | 'youtube';
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'downloading' | 'playable' | 'failed' | 'expired';
      /** Title */
      title: string;
    };
    /** ContentItem */
    ContentItem: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Duration Ms */
      duration_ms: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Source
       * @enum {string}
       */
      source: 'upload' | 'youtube';
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'downloading' | 'playable' | 'failed' | 'expired';
      /** Title */
      title: string;
    };
    /** ContentList */
    ContentList: {
      /** Items */
      items: components['schemas']['ContentItem'][];
      /**
       * Next Cursor
       * @description Pass as `cursor` for the next page
       */
      next_cursor: string | null;
    };
    /** Credentials */
    Credentials: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LibraryItem */
    LibraryItem: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Duration Ms */
      duration_ms: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** @description Status of the newest practice session on this item; null when none */
      last_session_status: components['schemas']['SessionStatus'] | null;
      /**
       * Source
       * @enum {string}
       */
      source: 'upload' | 'youtube';
      /**
       * Status
       * @description Processing status of the clip's media
       * @enum {string}
       */
      status: 'pending' | 'downloading' | 'playable' | 'failed' | 'expired';
      /** Title */
      title: string;
    };
    /** LibraryPage */
    LibraryPage: {
      /** Items */
      items: components['schemas']['LibraryItem'][];
      /**
       * Next Cursor
       * @description Pass as `cursor` for the next page
       */
      next_cursor: string | null;
    };
    /** Me */
    Me: {
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
      /** Email Verified */
      email_verified: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** PasswordReset */
    PasswordReset: {
      /** Password */
      password: string;
      /** Token */
      token: string;
    };
    /** PasswordResetRequest */
    PasswordResetRequest: {
      /** Email */
      email: string;
    };
    /** PasswordResetRequested */
    PasswordResetRequested: {
      /** Detail */
      detail: string;
    };
    /**
     * SessionStatus
     * @enum {string}
     */
    SessionStatus: 'active' | 'completed' | 'abandoned';
    /** StorageUse */
    StorageUse: {
      /** Max File Bytes */
      max_file_bytes: number;
      /** Quota Bytes */
      quota_bytes: number;
      /** Used Bytes */
      used_bytes: number;
    };
    /** UploadRequest */
    UploadRequest: {
      /** Content Type */
      content_type: string;
      /** Filename */
      filename: string;
      /**
       * Size Bytes
       * @description The file's exact size; storage refuses any other
       */
      size_bytes: number;
    };
    /**
     * UploadTarget
     * @description Where and how the browser sends the file: one PUT with exactly these headers.
     */
    UploadTarget: {
      /**
       * Expires At
       * Format: date-time
       * @description The upload must start before this time
       */
      expires_at: string;
      /** Headers */
      headers: {
        [key: string]: string;
      };
      /**
       * Method
       * @constant
       */
      method: 'PUT';
      /**
       * Upload Id
       * Format: uuid
       */
      upload_id: string;
      /** Url */
      url: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Credentials'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  request_password_reset_api_v1_auth_password_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PasswordResetRequested'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reset_password_api_v1_auth_password_reset_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordReset'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Credentials'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_contents_api_v1_contents_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContentList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_content_api_v1_contents_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Retry-safe key for this submission */
        'Idempotency-Key'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmUpload'];
      };
    };
    responses: {
      /** @description Already confirmed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContentItem'];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContentItem'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_content_api_v1_contents__content_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        content_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContentDetail'];
        };
      };
      /** @description Not in your library */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  events_api_v1_events_get: {
    parameters: {
      query?: never;
      header?: {
        'last-event-id'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A Server-Sent Events stream of the learner's events: job.progress, content.ready, grade.ready, attempt.voided and resync. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  library_contents_api_v1_library_contents_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LibraryPage'];
        };
      };
      /** @description Not modified since the ETag in If-None-Match */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
    };
  };
  play_media_api_v1_media__media_object_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        media_object_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to a short-lived signed storage URL */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No item of yours uses this media object */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not playable yet (`media_not_ready`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  media_peaks_api_v1_media__media_object_id__peaks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        media_object_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to a short-lived signed storage URL */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No item of yours uses this media object */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not playable yet (`media_not_ready`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_upload_api_v1_uploads_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UploadRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadTarget'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_usage_api_v1_uploads_usage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StorageUse'];
        };
      };
    };
  };
  cancel_upload_api_v1_uploads__upload_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        upload_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
